seservices:
  - type: web
    name: php-app
    env: docker
    plan: free
    buildCommand: "docker build -t php-app ."     # Construire l'image Docker
    startCommand: "docker run -p 3000:3000 php-app"  # Exécuter l'image Docker et exposer le port 3000
    regions:
      - oregon  # Choisis la région où déployer ton service
